### ISSUE TITLE
Error demon_bed_fans_monitor_v1.3

### ISSUE THREAD

**Issue by Mad-Virus** [3DPrintDemon/Demon_Klipper_Essentials_Unified#19]
After last Update of demon_bed_fans_monitor_v1.3

Error loading template 'delayed_gcode _BED_FAN_MONITOR:gcode': jinja2.exceptions.TemplateSyntaxError: unexpected '=='
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/extras/gcode_macro.py", line 51, in __init__
    self.template = env.from_string(script)
  File "/home/biqu/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/biqu/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/biqu/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/biqu/klippy-env/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 5, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '=='
Config error
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/extras/gcode_macro.py", line 51, in __init__
    self.template = env.from_string(script)
  File "/home/biqu/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/biqu/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/biqu/klippy-env/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/biqu/klippy-env/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 5, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/klippy.py", line 130, in _connect
    self._read_config()
  File "/home/biqu/klipper/klippy/klippy.py", line 123, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/biqu/klipper/klippy/klippy.py", line 112, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/biqu/klipper/klippy/extras/delayed_gcode.py", line 54, in load_config_prefix
    return DelayedGcode(config)
  File "/home/biqu/klipper/klippy/extras/delayed_gcode.py", line 16, in __init__
    self.timer_gcode = gcode_macro.load_template(config, 'gcode')
  File "/home/biqu/klipper/klippy/extras/gcode_macro.py", line 81, in load_template
    return TemplateWrapper(self.printer, self.env, name, script)
  File "/home/biqu/klipper/klippy/extras/gcode_macro.py", line 56, in __init__
    raise printer.config_error(msg)
configparser.Error: Error loading template 'delayed_gcode _BED_FAN_MONITOR:gcode': jinja2.exceptions.TemplateSyntaxError: unexpected '=='

**Comment by 3DPrintDemon** [comment]
Error corrected. Thanks for the heads up. Please download file again.
